export type ServiceRole = "teacher" | "student" | "parent" | "professional" | "coder";
export type ServiceCategory =
    | "assessment"
    | "feedback"
    | "insights"
    | "content"
    | "tutoring"
    | "career"
    | "admin"
    | "translation"
    | "study"
    | "research"
    | "interview"
    | "collaboration";

export type ServiceStatus = "available" | "beta" | "coming-soon";

export interface ServiceItem {
    id: string;
    title: string;
    description: string;
    roles: ServiceRole[];
    categories: ServiceCategory[];
    status: ServiceStatus;
    ctaLabel: string;
    ctaHref: string;
    inputs: string[];
    outputs: string[];
}

export const ROLE_LABELS: Record<ServiceRole, string> = {
    teacher: "Teachers",
    student: "Students",
    parent: "Parents",
    professional: "Working Professionals",
    coder: "Coders",
};

export const ROLE_DESCRIPTIONS: Record<ServiceRole, string> = {
    teacher: "Automate grading, generate assessments, and unlock class-wide insights.",
    student: "Get tutoring, feedback, and practice tools tailored to your learning.",
    parent: "Track progress, get recommendations, and support learning at home.",
    professional: "Upskill with targeted learning paths and interview prep.",
    coder: "Practice, debug, and learn with AI coding copilots.",
};

export const CATEGORY_LABELS: Record<ServiceCategory, string> = {
    assessment: "Assessment",
    feedback: "Feedback",
    insights: "Insights",
    content: "Content",
    tutoring: "Tutoring",
    career: "Career",
    admin: "Admin",
    translation: "Translation",
    study: "Study",
    research: "Research",
    interview: "Interview",
    collaboration: "Collaboration",
};

export const SERVICES: ServiceItem[] = [
    {
        id: "teacher-auto-grading",
        title: "AI Grading Assistant",
        description: "Upload assignments and rubrics to auto-grade with confidence scoring.",
        roles: ["teacher"],
        categories: ["assessment", "feedback", "admin"],
        status: "beta",
        ctaLabel: "Open Teacher Dashboard",
        ctaHref: "/teacher",
        inputs: ["Assignment files", "Rubric or mark scheme"],
        outputs: ["Scores per student", "Feedback highlights", "Confidence levels"],
    },
    {
        id: "teacher-test-variants",
        title: "Personalized Test Variants",
        description: "Generate equivalent exam versions to reduce cheating and boost fairness.",
        roles: ["teacher"],
        categories: ["assessment", "content"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/teacher-test-variants",
        inputs: ["Master test", "Difficulty targets", "Question bank"],
        outputs: ["Student-specific variants", "Equivalence report"],
    },
    {
        id: "teacher-class-insights",
        title: "Class Insights",
        description: "Analyze performance trends and identify concepts needing reinforcement.",
        roles: ["teacher"],
        categories: ["insights", "feedback"],
        status: "beta",
        ctaLabel: "Open Teacher Dashboard",
        ctaHref: "/teacher",
        inputs: ["Assessment results", "Class roster"],
        outputs: ["Topic mastery map", "Rankings", "Intervention suggestions"],
    },
    {
        id: "teacher-quizbuilder",
        title: "Video-to-Quiz Builder",
        description: "Create quizzes, notes, and lesson plans from YouTube lectures.",
        roles: ["teacher", "student"],
        categories: ["content", "assessment"],
        status: "beta",
        ctaLabel: "Open Quiz Builder",
        ctaHref: "/services/quiz-builder",
        inputs: ["Video or playlist URL"],
        outputs: ["Transcript", "Lesson plan", "Quiz questions"],
    },
    {
        id: "teacher-lecture-summaries",
        title: "Lecture Summarizer",
        description: "Generate concise lecture summaries and key takeaways.",
        roles: ["teacher", "student"],
        categories: ["content", "study"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/teacher-lecture-summaries",
        inputs: ["Lecture notes", "Slides", "Recording transcript"],
        outputs: ["Summary", "Key concepts", "Quick review notes"],
    },
    {
        id: "teacher-syllabus-alignment",
        title: "Syllabus Alignment",
        description: "Align assessments with learning outcomes and standards.",
        roles: ["teacher"],
        categories: ["admin", "insights"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/teacher-syllabus-alignment",
        inputs: ["Syllabus", "Learning outcomes"],
        outputs: ["Coverage map", "Gap analysis"],
    },
    {
        id: "teacher-multilingual-quizzes",
        title: "Multilingual Quiz Translation",
        description: "Instantly translate quizzes for multilingual classrooms.",
        roles: ["teacher", "student"],
        categories: ["translation", "assessment"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/teacher-multilingual-quizzes",
        inputs: ["Quiz content", "Target languages"],
        outputs: ["Localized quiz versions"],
    },
    {
        id: "student-ai-tutor",
        title: "AI Tutor (RAG)",
        description: "Ask questions and get grounded answers from your course materials.",
        roles: ["student"],
        categories: ["tutoring", "study"],
        status: "beta",
        ctaLabel: "Open Mentor",
        ctaHref: "/mentor",
        inputs: ["Course docs", "Student questions"],
        outputs: ["Context-aware explanations", "Citations from materials"],
    },
    {
        id: "student-writing-coach",
        title: "Writing Coach",
        description: "Get section-level feedback and improvement suggestions.",
        roles: ["student"],
        categories: ["feedback", "study"],
        status: "beta",
        ctaLabel: "Open Writing Coach",
        ctaHref: "/services/writing-coach",
        inputs: ["Essay or draft"],
        outputs: ["Strengths", "Improvement suggestions"],
    },
    {
        id: "student-study-guides",
        title: "Personalized Study Guides",
        description: "Generate study guides tailored to your weak areas.",
        roles: ["student"],
        categories: ["study", "insights"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/student-study-guides",
        inputs: ["Past results", "Topics list"],
        outputs: ["Study plan", "Practice checklist"],
    },
    {
        id: "student-practice-quizzes",
        title: "Practice Quiz Generator",
        description: "Create quick quizzes to reinforce key concepts.",
        roles: ["student"],
        categories: ["assessment", "study"],
        status: "beta",
        ctaLabel: "Try Practice",
        ctaHref: "/tracks",
        inputs: ["Topic", "Difficulty"],
        outputs: ["Quiz questions", "Explanations"],
    },
    {
        id: "student-language-companion",
        title: "Language Learning Companion",
        description: "Practice grammar and conversation with an AI partner.",
        roles: ["student"],
        categories: ["tutoring", "study"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/student-language-companion",
        inputs: ["Target language", "Proficiency level"],
        outputs: ["Conversation practice", "Corrections"],
    },
    {
        id: "student-office-hours",
        title: "Virtual Office Hours Assistant",
        description: "Get instant answers to common course questions.",
        roles: ["student", "teacher"],
        categories: ["tutoring", "admin"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/student-office-hours",
        inputs: ["Course FAQs", "Policies"],
        outputs: ["Instant answers", "Resource links"],
    },
    {
        id: "parent-progress",
        title: "Progress Tracker",
        description: "Monitor learning progress with clear milestones.",
        roles: ["parent"],
        categories: ["insights"],
        status: "beta",
        ctaLabel: "View Parent Dashboard",
        ctaHref: "/parent/dashboard",
        inputs: ["Student activity data"],
        outputs: ["Progress dashboard", "Weekly summaries"],
    },
    {
        id: "parent-study-recs",
        title: "Learning Recommendations",
        description: "Suggested resources based on learning gaps.",
        roles: ["parent"],
        categories: ["study", "insights"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/parent-study-recs",
        inputs: ["Student performance data"],
        outputs: ["Recommended resources", "Next steps"],
    },
    {
        id: "parent-tutor-connect",
        title: "Tutor Matching",
        description: "Connect with tutors tailored to your child’s needs.",
        roles: ["parent"],
        categories: ["collaboration", "admin"],
        status: "available",
        ctaLabel: "Find Tutors",
        ctaHref: "/become-a-tutor",
        inputs: ["Subject needs", "Schedule preferences"],
        outputs: ["Matched tutor list"],
    },
    {
        id: "professional-interview-prep",
        title: "Interview Prep Studio",
        description: "Mock interviews with AI feedback and scoring.",
        roles: ["professional"],
        categories: ["interview", "feedback"],
        status: "available",
        ctaLabel: "Start Mock Interview",
        ctaHref: "/mock-interview",
        inputs: ["Role focus", "Skill targets"],
        outputs: ["Interview transcript", "Scores", "Feedback"],
    },
    {
        id: "professional-career-paths",
        title: "Skill-to-Role Pathways",
        description: "Map skills to job pathways and recommendations.",
        roles: ["professional"],
        categories: ["career", "insights"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/professional-career-paths",
        inputs: ["Resume or skills list"],
        outputs: ["Role matches", "Learning gaps"],
    },
    {
        id: "professional-research-assist",
        title: "Research Assistant",
        description: "Speed up literature review and concept synthesis.",
        roles: ["professional", "student"],
        categories: ["research", "content"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/professional-research-assist",
        inputs: ["Topic", "Paper list"],
        outputs: ["Summaries", "Key findings"],
    },
    {
        id: "coder-debug-coach",
        title: "Debugging Coach",
        description: "Get targeted debugging hints and explanations.",
        roles: ["coder", "student"],
        categories: ["feedback", "tutoring"],
        status: "available",
        ctaLabel: "Open Coding Arena",
        ctaHref: "/arena",
        inputs: ["Code snippet", "Error logs"],
        outputs: ["Debug hints", "Suggested fixes"],
    },
    {
        id: "coder-context-explainer",
        title: "Code Explanation Assistant",
        description: "Explain code and generate step-by-step walkthroughs.",
        roles: ["coder", "student"],
        categories: ["study", "tutoring"],
        status: "available",
        ctaLabel: "Open Mentor",
        ctaHref: "/mentor",
        inputs: ["Code snippet"],
        outputs: ["Plain-language explanation", "Key concepts"],
    },
    {
        id: "coder-prompt-quiz",
        title: "Prompt Engineering Quiz Bank",
        description: "Practice prompt patterns and improve LLM skills.",
        roles: ["coder", "student", "professional"],
        categories: ["assessment", "study"],
        status: "coming-soon",
        ctaLabel: "Learn More",
        ctaHref: "/services/coder-prompt-quiz",
        inputs: ["Prompt pattern selection"],
        outputs: ["Quiz questions", "Answer keys"],
    },
];
